#!/bin/sh
# generated by ssh-paste v__VERSION__ -- managed by `ssh-paste setup`, do not edit
spool=__SPOOL__
png="$spool/clip.png"
txt="$spool/clip.txt"

fail() { printf '%s\n' "$1" >&2; exit "$2"; }

mode=paste
mime=""
while [ $# -gt 0 ]; do
  case "$1" in
    -l|--list-types) mode=list ;;
    --type|-t) mime="$2"; shift ;;
    --no-newline|-n) ;;
    *) fail "ssh-paste shim: unsupported wl-paste argument: $1" 2 ;;
  esac
  shift
done

if [ "$mode" = list ]; then
  if [ -f "$png" ]; then printf 'image/png\n'
  elif [ -f "$txt" ]; then printf 'text/plain;charset=utf-8\ntext/plain\n'
  else fail "No selection" 1
  fi
  exit 0
fi

case "$mime" in
  image/png)
    [ -f "$png" ] || fail "No suitable type of content copied" 1
    exec cat "$png" ;;
  ""|text/plain*)
    [ -f "$txt" ] || fail "No selection" 1
    exec cat "$txt" ;;
  *)
    fail "No suitable type of content copied" 1 ;;
esac
