#!/bin/sh
# generated by ssh-paste v__VERSION__ -- managed by `ssh-paste setup`, do not edit
spool=__SPOOL__
port=__PORT__
png="$spool/clip.png"
txt="$spool/clip.txt"

fail() { printf '%s\n' "$1" >&2; exit "$2"; }

kind=""
if command -v curl >/dev/null 2>&1; then
  kind=$(curl -sf --connect-timeout 1 --max-time 5 "http://127.0.0.1:$port/kind" 2>/dev/null) || kind=""
else
  echo "ssh-paste shim: curl not found; using spool only" >&2
fi

src=spool
have_image=false
have_text=false
case "$kind" in
  image/png) src=tunnel; have_image=true ;;
  text/plain) src=tunnel; have_text=true ;;
  *)
    [ -f "$png" ] && have_image=true
    [ -f "$txt" ] && have_text=true
    ;;
esac

emit_image() {
  if [ "$src" = tunnel ]; then exec curl -sf --max-time 20 "http://127.0.0.1:$port/data/image"; fi
  exec cat "$png"
}

emit_text() {
  if [ "$src" = tunnel ]; then exec curl -sf --max-time 20 "http://127.0.0.1:$port/data/text"; fi
  exec cat "$txt"
}

mode=paste
mime=""
while [ $# -gt 0 ]; do
  case "$1" in
    -l|--list-types) mode=list ;;
    --type|-t) mime="$2"; shift ;;
    --no-newline|-n) ;;
    *) fail "ssh-paste shim: unsupported wl-paste argument: $1" 2 ;;
  esac
  shift
done

if [ "$mode" = list ]; then
  if [ "$have_image" = true ]; then printf 'image/png\n'
  elif [ "$have_text" = true ]; then printf 'text/plain;charset=utf-8\ntext/plain\n'
  else fail "No selection" 1
  fi
  exit 0
fi

case "$mime" in
  image/png)
    [ "$have_image" = true ] || fail "No suitable type of content copied" 1
    emit_image ;;
  ""|text/plain*)
    [ "$have_text" = true ] || fail "No selection" 1
    emit_text ;;
  *)
    fail "No suitable type of content copied" 1 ;;
esac
