#!/bin/sh
# generated by ssh-paste v__VERSION__ -- managed by `ssh-paste setup`, do not edit
spool=__SPOOL__
png="$spool/clip.png"
txt="$spool/clip.txt"

fail() { printf '%s\n' "$1" >&2; exit "$2"; }

target=""
readout=false
while [ $# -gt 0 ]; do
  case "$1" in
    -selection) shift ;;
    -t) target="$2"; shift ;;
    -o) readout=true ;;
    *) fail "ssh-paste shim: unsupported xclip argument: $1" 2 ;;
  esac
  shift
done
[ "$readout" = true ] || fail "ssh-paste shim: only reading (-o) is supported" 2

case "$target" in
  TARGETS)
    if [ -f "$png" ]; then printf 'TARGETS\nimage/png\n'
    elif [ -f "$txt" ]; then printf 'TARGETS\nUTF8_STRING\nSTRING\ntext/plain\n'
    else fail "Error: There is no owner for the CLIPBOARD selection." 1
    fi ;;
  image/png)
    [ -f "$png" ] || fail "Error: target image/png not available" 1
    exec cat "$png" ;;
  ""|text/plain|UTF8_STRING|STRING)
    [ -f "$txt" ] || fail "Error: target text/plain not available" 1
    exec cat "$txt" ;;
  *)
    fail "Error: target $target not available" 1 ;;
esac
