#!/bin/sh
# generated by ssh-paste v__VERSION__ -- managed by `ssh-paste setup`, do not edit
spool=__SPOOL__
port=__PORT__
png="$spool/clip.png"
txt="$spool/clip.txt"

fail() { printf '%s\n' "$1" >&2; exit "$2"; }

kind=""
tunnel_empty=false
if [ "${SSH_PASTE_SOURCE:-}" = spool ]; then
  :
elif command -v curl >/dev/null 2>&1; then
  if kind=$(curl -sf --connect-timeout 1 --max-time 5 "http://127.0.0.1:$port/kind" 2>/dev/null); then
    :
  else
    [ $? -eq 22 ] && tunnel_empty=true
    kind=""
  fi
else
  echo "ssh-paste shim: curl not found; using spool only" >&2
fi

src=spool
have_image=false
have_text=false
case "$kind" in
  image/png) src=tunnel; have_image=true ;;
  text/plain) src=tunnel; have_text=true ;;
  *)
    if [ "$tunnel_empty" = false ]; then
      [ -f "$png" ] && have_image=true
      [ -f "$txt" ] && have_text=true
    fi
    ;;
esac

emit_image() {
  if [ "$src" = tunnel ]; then exec curl -sf --connect-timeout 1 --max-time 20 "http://127.0.0.1:$port/data/image"; fi
  exec cat "$png"
}

emit_text() {
  if [ "$src" = tunnel ]; then exec curl -sf --connect-timeout 1 --max-time 20 "http://127.0.0.1:$port/data/text"; fi
  exec cat "$txt"
}

target=""
readout=false
while [ $# -gt 0 ]; do
  case "$1" in
    -selection) shift ;;
    -t) target="$2"; shift ;;
    -o) readout=true ;;
    *) fail "ssh-paste shim: unsupported xclip argument: $1" 2 ;;
  esac
  shift
done
[ "$readout" = true ] || fail "ssh-paste shim: only reading (-o) is supported" 2

case "$target" in
  TARGETS)
    if [ "$have_image" = true ]; then printf 'TARGETS\nimage/png\n'
    elif [ "$have_text" = true ]; then printf 'TARGETS\nUTF8_STRING\nSTRING\ntext/plain\n'
    else fail "Error: There is no owner for the CLIPBOARD selection." 1
    fi ;;
  image/png)
    [ "$have_image" = true ] || fail "Error: target image/png not available" 1
    emit_image ;;
  ""|text/plain|UTF8_STRING|STRING)
    [ "$have_text" = true ] || fail "Error: target text/plain not available" 1
    emit_text ;;
  *)
    fail "Error: target $target not available" 1 ;;
esac
