pub const MARKER_PREFIX: &str = "# generated by ssh-paste v";

const XCLIP: &str = include_str!("../templates/xclip.sh");
const WL_PASTE: &str = include_str!("../templates/wl-paste.sh");

fn render(template: &str, spool_expr: &str, port: u16) -> String {
    template
        .replace("__VERSION__", env!("CARGO_PKG_VERSION"))
        .replace("__SPOOL__", spool_expr)
        .replace("__PORT__", &port.to_string())
}

pub fn render_xclip(spool_expr: &str, port: u16) -> String {
    render(XCLIP, spool_expr, port)
}

pub fn render_wl_paste(spool_expr: &str, port: u16) -> String {
    render(WL_PASTE, spool_expr, port)
}
