pub const MARKER_PREFIX: &str = "# generated by ssh-paste v";

const XCLIP: &str = include_str!("../templates/xclip.sh");
const WL_PASTE: &str = include_str!("../templates/wl-paste.sh");

fn render(template: &str, spool_expr: &str) -> String {
    template
        .replace("__VERSION__", env!("CARGO_PKG_VERSION"))
        .replace("__SPOOL__", spool_expr)
}

pub fn render_xclip(spool_expr: &str) -> String {
    render(XCLIP, spool_expr)
}

pub fn render_wl_paste(spool_expr: &str) -> String {
    render(WL_PASTE, spool_expr)
}
